#!/bin/bash
# uses a hybrid of bash and python to syntax color output, doesn't work in all situations
# I'd like to replace this with a vim script that exits but leaves the text in the buffer

  if [ ! -t 0 ];then
    file=/dev/stdin
  elif [ -f $1 ];then
    file=$1
  else
    echo "Usage: $0 code.c"
    echo "or e.g. head code.c|$0"
    exit 1
  fi
  pygmentize -f terminal -g $file

