#!/bin/sh


DEFAULT="[37;40m"
PINK="[35;40m"
GREEN="[32;40m"
ORANGE="[33;40m"

function PWD { tmp=${PWD%/*/*}; [ ${#tmp} -gt 0 -a "$tmp" != "$PWD" ] && echo ${PWD:${#tmp}+1} || echo $PWD; }
function title { echo -ne "\\033]0;$*\007"; }

git_dirty() {
    git status 2> ~/.nil \
    | awk 'index($0,"Untracked files:") { unknown = 1 } 
           index($0,"modified:") { changed = 1 }
           END {
             if (changed) printf "!"
             else if (unknown) printf "?" 
           }'
}

git_branch() {
    git branch 2> ~/.nil | \
        awk '$1 =="*" { printf "\033[37;0m on \033[35;40m" $2 }'
    #git bookmarks 2> ~/.nil | \
    #    awk '/\*/ { printf "\033[37;0m at \033[33;40m" $2 }'
}

export PS1='\[$(title $(PWD))\]\
\n\e${PINK}\u \
\e${DEFAULT}at \e${ORANGE}\h \
\e${DEFAULT}in \e${GREEN}\w\
$(git_branch)\e${GREEN}$(git_dirty)\
\e${DEFAULT}\n$ '
