#!/usr/bin/env bash

cd `dirname $0`

dir=`pwd`
bin_dir_name=bin
xbin_dir_name=xbin
bin_dir=$dir/$bin_dir_name
xbin_dir=$dir/$xbin_dir_name

echo Pulling remote submodules...
git submodule init
git submodule update

echo Preparing external binaries...

for f in external/*; do
  echo getting list of executables from $f
  find $f -maxdepth 2 -type f -perm /a+x -exec cp -v {} $xbin_dir/ \;
  echo copying executables to $xbin_dir
done


echo Creating symlinks...
ln -s $dir/$bin_dir_name ~/
ln -s $dir/$xbin_dir_name ~/

echo Done!
