#!/usr/bin/env bash

echo -ne pushd:\ 
pushd `dirname $0`

dir=`pwd`
bin_dir_name=bin
xbin_dir_name=xbin
bin_dir=$dir/$bin_dir_name
xbin_dir=$dir/$xbin_dir_name

echo Pulling remote submodules...
git submodule init
git submodule update

echo Preparing external binaries...
for f in external/*
  do
    echo getting list of executables from $f
    find $f -maxdepth 1 -type f -perm /a+x -exec cp -v {} $xbin_dir/ \;
    echo copying executables to $xbin_dir
  done
#end for

echo Creating symlinks...
#ln $dir/$bin_dir_name ~/$bin_dir_name
#ln $dir/$xbin_dir_name ~/$xbin_dir_name

echo Done!
