#!/bin/bash

function test_stdnil {
  for x in {1..1000}; do
    echo foo | stdnil;
  done;
}

function test_file {
  for x in {1..1000}; do
    echo bar > ~/.nil;
  done;
}

function test_exit {
  for x in {1..1000}; do
    echo baz | exit 0;
  done;
}

function stdnil {
  exit 0;
}

echo -ne "\nstdnil"
time test_stdnil

echo -ne "\nfile"
time test_file

echo -ne "\nexit"
time test_exit

